### ISSUE TITLE
With 10 million keys finds only first few million keys

### ISSUE THREAD

**Issue by dimaa6** [myui/btree4j#1]
I have tried the following code:

```
      BTreeIndex btree = new BTreeIndex(indexFile, false);
      btree.init(false);

      Random rand = new Random();
      for (int i = 0; i < 10000000; i++) {
        long nt = System.nanoTime(), val = rand.nextLong();
        Value key = new Value(String.valueOf(nt) + val);
        Value value = new Value(val);
        if (i % 10000 == 0) {
          System.out.println(i + " " + key + " " + btree.addValue(key, value));
        } else {
          btree.addValue(key, value);
        }
      }

```

Then in another method I open index file and try to search for keys:

```
       BTreeIndex btree = new BTreeIndex(indexFile, false);
       Value val = btree.getValue(new Value("205388120935395-497341292157541218"));
       System.out.println(Primitives.getLong(val.getData()));

```
On first few million, it works, but then throws NullPointerException inside Value class. Am I doing something wrong?

**Comment by myui** [comment]
Hi @dimaa6,  

Sorry to be late. 

Could you provide stacktrace? 

Also, did you run [flush](https://github.com/myui/btree4j/blob/master/src/main/java/btree4j/BTreeIndex.java#L550) that writes in-memory cached pages to disk? Complete code will help to investigate your issue.

**Comment by dimaa6** [comment]
Added flush after every millionth addValue. Did not fix the issue. Part of stack trace concerning btree4j:

java.lang.NullPointerException
	at btree4j.Value.<init>(Value.java:48)
	at btree4j.BTreeIndex.getValue(BTreeIndex.java:122)

**Comment by myui** [comment]
@dimaa6 It should return null instead of NPE if key is not existing.

You need to call `flush` in the end of for-loop. For each 10000 is not enough (suppose 10001).
Is `205388120935395-497341292157541218` really registered?

**Comment by myui** [comment]
Could you provide re-producible test code (entire) if possible?

**Comment by dimaa6** [comment]
Writing:

```
    File indexFile = new File(my_path_to_index_file);
    BTreeIndex btree = new BTreeIndex(indexFile, false);
    try {
      btree.init(false);

      Random rand = new Random();
      for (int i = 0; i < 10000000; i++) {
        long nt = System.nanoTime(), val = rand.nextLong();
        Value key = new Value(String.valueOf(nt) + val);
        Value value = new Value(val);
        if (i % 10000 == 0) {
          System.out.println(i + " " + key + " " + btree.addValue(key, value));
        } else {
          btree.addValue(key, value);
        }
        if (i % 1000000 == 0) {
          btree.flush();
        }
      }
      btree.flush();
      btree.close();
    }
    catch (Exception e) {
      e.printStackTrace();
    }

```

Copy the output. Now take key close to the end and use it in getValue call:

```
    File indexFile = new File("my_path_to_index_file");
    BTreeIndex btree = new BTreeIndex(indexFile, false);
    try {
      btree.init(false);

      Value val = btree.getValue(new Value("606313838488572-5317002158191699811"));
      System.out.println(Primitives.getLong(val.getData()));
    }
    catch (Exception e) {
      e.printStackTrace();
    }

```

**Comment by myui** [comment]
@dimaa6 can be reproduced. Fixed in https://github.com/myui/btree4j/commit/e21f4dd69683a08c2e890739309868cc5ee0bf0b

It was a bug introduced in refactoring on the initial import.

**Comment by myui** [comment]
test passed https://github.com/myui/btree4j/blob/master/src/test/java/btree4j/BTreeIndexTest.java#L222
