### ISSUE TITLE
How do I obtain the 10 values of a key in ascending or descending order?

### ISSUE THREAD

**Issue by CodeDream-Mo** [myui/btree4j#19]

**Comment by CodeDream-Mo** [comment]
@myui

**Comment by myui** [comment]
@CodeDream-Mo 

BTreeIndexDup allows multiple values for a key.
https://github.com/myui/btree4j/blob/master/src/test/java/btree4j/BTreeIndexTest.java#L128

To get values for BTreeIndexDup, search() can be used. Values for a key is `not ordered`.

```java
BTreeIndexDup btree = new BTreeIndexDup(tmpFile);
btree.init(false);
btree.addValue(new Value(k1), new Value(v1));
btree.addValue(new Value(k1), new Value(v2));
...
btree.addValue(new Value(k1), new Value(v10));
List<Integer> results = Arrays.asList();
btree.search(new IndexConditionEQ(), new BTreeCallback() {
   public boolean indexInfo(Value key, byte[] value) {
       int v = Primitives.getInt(value);
       results.add(v);
   }
}
```

You need to sort values something like `Arrays.sort(results, Collections.reverseOrder());`.

**Comment by myui** [comment]
Close as answered. Please reopen if you have additional questions.

**Comment by ChromMob** [comment]
I would be curious about the same but I am using the normal BTree as I handle indexes myself. Oh the method is the same sorry
