### ISSUE TITLE
Distribute artifacts from Maven Central

### ISSUE THREAD

**Issue by myui** [myui/btree4j#5]
- [x] fix pom.xml
- [x] sync to Sonatype

**Comment by devcsrj** [comment]
Hello! Any ETA on the release?

**Comment by myui** [comment]
will release to sonatype ~in few days. Release v0.9.0 as it is.~

**Comment by myui** [comment]
blocked by https://github.com/myui/btree4j/pull/8

**Comment by jacobmou** [comment]
Really look forward to seeing this get released in the future. any ETA?

**Comment by myui** [comment]
@jacobmou @devcsrj 

Published to maven central. 
https://repo1.maven.org/maven2/io/github/myui/btree4j/

```
<dependency>
    <groupId>io.github.myui</groupId>
    <artifactId>btree4j</artifactId>
    <version>0.9.0</version>
</dependency>
```
