### ISSUE TITLE
Atomicity and consistency

### ISSUE THREAD

**Issue by Borbarad13** [myui/btree4j#9]
Hey MyUi,

less an issue, but more a question: How ACID compliant are the methods on the tree (especially atomicity)?

If for example the JVM shuts down (planned or as a fault) during the following method call

> btree.addValue(k, v);

would then there be a risk that the whole tree might (a) or parts of the tree (b) might be corrupt or is there no such risk (c)? Any hints regarding the ACID level compliance in the description would be greatly appreciated.

Kind regards,
Borbarad13

**Comment by myui** [comment]
btree4j does not aim at ACID compliance. Better to do WAL outside b+-tree (as DBMS do).

When adding a value to B+-tree, insertion is done in memory. Disk still is called when [flush](https://github.com/myui/btree4j/blob/master/src/main/java/btree4j/BTree.java#L468) is called or BufferManager (LRU) [select victim page](https://github.com/myui/btree4j/blob/master/src/main/java/btree4j/BTree.java#L156) to page out.

**Comment by Borbarad13** [comment]
Thanks for getting back to this, MyUi!
